### ISSUE TITLE
investigar como leer el sensor de corriente.

### ISSUE THREAD

**Issue by enriquewph** [enriquewph/PowerMike#1]
usar ads1115 + sct-013-100

[guia en internet](https://www.poweruc.pl/blogs/news/non-invasive-sensor-yhdc-sct013-000-ct-used-with-arduino-sct-013)
[pdf ads1115](https://www.ti.com/lit/ds/symlink/ads1113.pdf?ts=1632242291830)

**Comment by enriquewph** [comment]
https://github.com/pasko-zh/brzo_i2c

**Comment by enriquewph** [comment]
viendo un toque como debemos medir, para hacer el calculo RMS necesitamos aprox 12 muestras por ciclo, para tener un error del 1%. Eso lo logramos con 50Hz * 12 -> 600 M/s.
El ADS1115 tiene un maximo de 860 M/s. pero eso seria usando un solo canal, usando 2, basicamente lo dividimos y quedarian aprox. 9 muestras por ciclo, lo cual nos aumenta mucho el error.

usemos 2, y si probando se puede con 1 genial. sino fue....

**Comment by enriquewph** [comment]
para q no se acumule error, necesitamos que la cantidad de muestras por segundo sea un multiplo de 50. osea que el adc no nos serviria... podemos probar con el ADS1015 que es de 12 bits pero sirve hasta 3300 M/s

**Comment by enriquewph** [comment]
3300 M/s nos da 66 muestras por ciclo. Si multiplexamos y usamos un canal para medir corriente y otro para tension, nos quedarian alrededor de 33 muestras por ciclo.

**Comment by enriquewph** [comment]
la interrupcion que debemos manejar debe ejecutarse en menos de 0,3 milisegundos o rompemos el timing. Estaria muy jugado.
sino, usamos 2400M/s, y nos queda midiendo tension y corriente unas 24 mestras por ciclo, y el codigo de interrupcion puede durar hasta 0,41ms

**Comment by lucasdavalle** [comment]
https://github.com/adafruit/Adafruit_ADS1X15 libreria de adafruit para arudino

**Comment by lucasdavalle** [comment]
> viendo un toque como debemos medir, para hacer el calculo RMS necesitamos aproximadamente 12 muestras por ciclo, para tener un error del 1%. Eso lo logramos con 50Hz * 12 -> 600 M / s. El ADS1115 tiene un máximo de 860 M / s. pero eso seria usando un solo canal, usando 2, basicamente lo dividimos y quedarian aprox. 9 muestras por ciclo, lo cual nos aumenta mucho el error.
> 
> usemos 2, y si probando se puede con 1 genial. sino fue ....

no entiendo por que no podriamos usar directamente 1 canal

**Comment by lucasdavalle** [comment]
https://programarfacil.com/blog/arduino-blog/sct-013-consumo-electrico-arduino/

**Comment by lucasdavalle** [comment]
https://www.youtube.com/watch?v=uRqT0gqZG6U

**Comment by enriquewph** [comment]
> > viendo un toque como debemos medir, para hacer el calculo RMS necesitamos aproximadamente 12 muestras por ciclo, para tener un error del 1%. Eso lo logramos con 50Hz * 12 -> 600 M / s. El ADS1115 tiene un máximo de 860 M / s. pero eso seria usando un solo canal, usando 2, basicamente lo dividimos y quedarian aprox. 9 muestras por ciclo, lo cual nos aumenta mucho el error.
> > usemos 2, y si probando se puede con 1 genial. sino fue ....
> 
> no entiendo por que no podriamos usar directamente 1 canal

1 canal para medir corriente
1 canal para medir tension
