### ISSUE TITLE
diseñar filtros pasabajos

### ISSUE THREAD

**Issue by enriquewph** [enriquewph/PowerMike#2]
como dice el titulo, con corte en 50Hz

**Comment by hjsalguero** [comment]
http://www.learningaboutelectronics.com/Articulos/Calculadora-de-filtro-paso-bajo.php#respuesta1
![image](https://user-images.githubusercontent.com/49728299/135342656-334128cd-0f15-47e6-bb2a-3a37442fcc86.png)

**Comment by enriquewph** [comment]
xd no hay R de 300 ohm que yo tenga, busquemos algo entre 0.1 y 1000nF

**Comment by hjsalguero** [comment]
sisi me lo habias dicho por wsp y lo pasé antes.

**Comment by JoacoSalguero** [comment]
Resistencias de cuanto tenes? Dame un rango

**Comment by hjsalguero** [comment]
![Screenshot_20211003-123333_Electrodoc.jpg](https://user-images.githubusercontent.com/49728299/135761214-cedd2b10-b772-47be-b7bb-595da6981f4f.jpg)
![Screenshot_20211003-123622_Electrodoc.jpg](https://user-images.githubusercontent.com/49728299/135761218-edd4a45c-2eb4-4cbe-82be-30bcd06903a8.jpg)
![Screenshot_20211003-123333_Electrodoc.jpg](https://user-images.githubusercontent.com/49728299/135761227-11ee48db-a787-4954-a35f-23246a7b68be.jpg)
![Screenshot_20211003-123933_Electrodoc.jpg](https://user-images.githubusercontent.com/49728299/135761263-313cac24-5ac4-4458-884c-e0ef757f20c4.jpg)

**Comment by hjsalguero** [comment]
Pasé varias opciones, si hay problemas con R o C que no hay pasaje rangos y vuelvo a calcular
